type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 4
terminals: 120
collect_pg_stat_statements: true
use_dist_in_explain : true
works:
    work:
        time_secs: 60
        active_terminals: 120
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table if exists table_4_cols_200b;
            - CREATE TABLE table_4_cols_200b (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, PRIMARY KEY (id));
        loadRules:
            -   table: table_4_cols_200b
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
                    -   name: col
                        count: 4
                        util: RandomAString
                        params: [ 2, 2 ]
        executeRules:
            -   workload: 200b_select
                run:
                    -   name: select_rowsize_200b
                        weight: 100
                        queries:
                            -   query: SELECT * from table_4_cols_200b where id=?
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 10000000 ]
                                count: 1




