type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 4
terminals: 60
collect_pg_stat_statements: true
use_dist_in_explain : true
works:
    work:
        time_secs: 60
        active_terminals: 60
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table if exists table_20_cols;
            - CREATE TABLE table_20_cols (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL, col1 INT, col2 INT, col3 INT, col4 INT, col5 INT, col6 INT, col7 INT, col8 INT, col9 INT, col10 INT, col11 INT, col12 INT, col13 INT, col14 INT, col15 INT, col16 INT, PRIMARY KEY (id));
        loadRules:
            -   table: table_20_cols
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
                    -   name: col
                        count: 16
                        util: RandomNumber
                        params: [ 1, 1000000 ]
        executeRules:
            -   workload: 20_col_insert
                run:
                    -   name: insert_with_20cols_test
                        weight: 100
                        queries:
                            -   query: insert into table_20_cols (k, c, pad, col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                                count: 1
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 1000000 ]
                                    -   util: RandomAString
                                        params: [ 120, 120 ]
                                    -   util: RandomAString
                                        params: [ 60, 60 ]
                                    -   util: RandomNumber
                                        count: 16
                                        params: [ 1, 1000000 ]
