type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 4
terminals: 120
collect_pg_stat_statements: true
use_dist_in_explain : true
works:
    work:
        time_secs: 600
        active_terminals: 120
        rate: unlimited
        warmup: 180
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table if exists table_4_cols;
            - CREATE TABLE table_4_cols (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL,  PRIMARY KEY (id));
        loadRules:
            -   table: table_4_cols
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
        executeRules:
            -   workload: 4_col_select
                run:
                    -   name: select_with_4cols_test
                        weight: 100
                        queries:
                            -   query: SELECT * from table_4_cols where id=?
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 10000000 ]
                                count: 1
