type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 5
terminals: 120
collect_pg_stat_statements: true
use_dist_in_explain : true
works:
    work:
        time_secs: 300
        active_terminals: 60
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table if exists table_rowsize_200b;
            - drop table if exists table_rowsize_1kb;
            - drop table if exists table_rowsize_5kb;
            - drop table if exists table_rowsize_25kb;
            - drop table if exists table_rowsize_125kb;
            - CREATE TABLE table_rowsize_200b (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, PRIMARY KEY (id));
            - CREATE TABLE table_rowsize_1kb (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, PRIMARY KEY (id));
            - CREATE TABLE table_rowsize_5kb (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, PRIMARY KEY (id));
            - CREATE TABLE table_rowsize_25kb (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, PRIMARY KEY (id));
            - CREATE TABLE table_rowsize_125kb (id SERIAL, k INTEGER DEFAULT '0' NOT NULL, c CHAR(120) DEFAULT '' NOT NULL, pad CHAR(60) DEFAULT '' NOT NULL, col1 TEXT, col2 TEXT, col3 TEXT, col4 TEXT, PRIMARY KEY (id));
            - ALTER SEQUENCE table_rowsize_200b_id_seq  cache 1000
            - ALTER SEQUENCE table_rowsize_1kb_id_seq  cache 1000
            - ALTER SEQUENCE table_rowsize_5kb_id_seq  cache 1000
            - ALTER SEQUENCE table_rowsize_25kb_id_seq  cache 1000
            - ALTER SEQUENCE table_rowsize_125kb_id_seq  cache 1000
        cleanup:
            - drop table if exists table_rowsize_200b;
            - drop table if exists table_rowsize_1kb;
            - drop table if exists table_rowsize_5kb;
            - drop table if exists table_rowsize_25kb;
            - drop table if exists table_rowsize_125kb;
        loadRules:
            -   table: table_rowsize_200b
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
                    -   name: col
                        count: 4
                        util: RandomAString
                        params: [ 2, 2 ]
            -   table: table_rowsize_1kb
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
                    -   name: col
                        count: 4
                        util: RandomAString
                        params: [ 100, 100 ]
            -   table: table_rowsize_5kb
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
                    -   name: col
                        count: 4
                        util: RandomAString
                        params: [ 1200, 1200 ]
            -   table: table_rowsize_25kb
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
                    -   name: col
                        count: 4
                        util: RandomAString
                        params: [ 5750, 5750 ]
            -   table: table_rowsize_125kb
                rows: 10000000
                columns:
                    -   name: k
                        util: RandomNumber
                        params: [ 1, 1000000 ]
                    -   name: c
                        util: RandomAString
                        params: [ 120, 120 ]
                    -   name: pad
                        util: RandomAString
                        params: [ 60, 60 ]
                    -   name: col
                        count: 4
                        util: RandomAString
                        params: [ 31200, 31200 ]
        executeRules:
            -   workload: 200b_select
                run:
                    -   name: select_rowsize_200b
                        weight: 100
                        queries:
                            -   query: SELECT * from table_rowsize_200b where id=?
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 10000000 ]
                                count: 1
            -   workload: 200b_insert
                run:
                    -   name: insert_rowsize_200b
                        weight: 100
                        queries:
                            -   query: insert into table_rowsize_200b(k, c, pad, col1, col2, col3, col4) values (?,?,?,?,?,?,?)
                                count: 1
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 1000000 ]
                                    -   util: RandomAString
                                        params: [ 120, 120 ]
                                    -   util: RandomAString
                                        params: [ 60, 60 ]
                                    -   util: RandomAString
                                        count: 4
                                        params: [ 2, 2 ]
            -   workload: 1kb_select
                run:
                    -   name: select_rowsize_1kb
                        weight: 100
                        queries:
                            -   query: SELECT * from table_rowsize_1kb where id=?
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 10000000 ]
                                count: 1
            -   workload: 1kb_insert
                run:
                    -   name: insert_rowsize_1kb
                        weight: 100
                        queries:
                            -   query: insert into table_rowsize_1kb (k, c, pad, col1, col2, col3, col4) values (?,?,?,?,?,?,?)
                                count: 1
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 1000000 ]
                                    -   util: RandomAString
                                        params: [ 120, 120 ]
                                    -   util: RandomAString
                                        params: [ 60, 60 ]
                                    -   util: RandomAString
                                        count: 4
                                        params: [ 100, 100 ]
            -   workload: 5kb_select
                run:
                    -   name: select_rowsize_5kb
                        weight: 100
                        queries:
                            -   query: SELECT * from table_rowsize_5kb where id=?
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 10000000 ]
                                count: 1
            -   workload: 5kb_insert
                run:
                    -   name: insert_rowsize_5kb
                        weight: 100
                        queries:
                            -   query: insert into table_rowsize_5kb (k, c, pad, col1, col2, col3, col4) values(?,?,?,?,?,?,?)
                                count: 1
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 1000000 ]
                                    -   util: RandomAString
                                        params: [ 120, 120 ]
                                    -   util: RandomAString
                                        params: [ 60, 60 ]
                                    -   util: RandomAString
                                        count: 4
                                        params: [ 1200, 1200 ]
            -   workload: 25kb_select
                run:
                    -   name: select_rowsize_25kb
                        weight: 100
                        queries:
                            -   query: SELECT * from table_rowsize_25kb where id=?
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 10000000 ]
                                count: 1
            -   workload: 25kbl_insert
                run:
                    -   name: insert_rowsize_25kb
                        weight: 100
                        queries:
                            -   query: insert into table_rowsize_25kb (k, c, pad, col1, col2, col3, col4) values (?,?,?,?,?,?,?)
                                count: 1
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 1000000 ]
                                    -   util: RandomAString
                                        params: [ 120, 120 ]
                                    -   util: RandomAString
                                        params: [ 60, 60 ]
                                    -   util: RandomAString
                                        count: 4
                                        params: [ 5750, 5750 ]
            -   workload: 125kb_select
                run:
                    -   name: select_rowsize_125kb
                        weight: 100
                        queries:
                            -   query: SELECT * from table_rowsize_125kb where id=?
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 10000000 ]
                                count: 1
            -   workload: 125kb_insert
                run:
                    -   name: insert_rowsize_125kb
                        weight: 100
                        queries:
                            -   query: insert into from table_rowsize_125kb (k, c, pad, col1, col2, col3, col4) values (?,?,?,?,?,?,?)
                                count: 1
                                bindings:
                                    -   util: RandomNumber
                                        params: [ 1, 1000000 ]
                                    -   util: RandomAString
                                        params: [ 120, 120 ]
                                    -   util: RandomAString
                                        params: [ 60, 60 ]
                                    -   util: RandomAString
                                        count: 4
                                        params: [ 31200, 31200 ]